/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dominio.Cliente;
import dao.*;

import java.sql.Connection;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

// Necessários para trabalhar as mensagens que aparecem na tela.
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.PLAIN_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author magno
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailCampoLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        entrarBotao = new javax.swing.JButton();
        passwordCampoLogin = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        criaNomeCampoLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        criaEmailCampoLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        criarContaBotao = new javax.swing.JButton();
        criaSenhaCampoLogin = new javax.swing.JPasswordField();
        confirmaSenhaCampoLogin = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Acesso usuário"));

        jLabel1.setText("Email");

        jLabel2.setText("Senha");

        entrarBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/locked-icon.png"))); // NOI18N
        entrarBotao.setText("Entrar");
        entrarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailCampoLogin)
                    .addComponent(passwordCampoLogin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 105, Short.MAX_VALUE)
                        .addComponent(entrarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailCampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordCampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(entrarBotao)
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo por aqui?"));

        jLabel3.setText("Nome");

        jLabel4.setText("Email");

        jLabel5.setText("Senha");

        criarContaBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/contact-icon.png"))); // NOI18N
        criarContaBotao.setText("Criar");
        criarContaBotao.setMaximumSize(new java.awt.Dimension(85, 46));
        criarContaBotao.setMinimumSize(new java.awt.Dimension(85, 46));
        criarContaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarContaBotaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Confirmar senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criaNomeCampoLogin)
                    .addComponent(criaEmailCampoLogin)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criaSenhaCampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(criarContaBotao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(confirmaSenhaCampoLogin, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criaNomeCampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criaEmailCampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criaSenhaCampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmaSenhaCampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(criarContaBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotaoActionPerformed
        // TODO add your handling code here:
        Cliente user = new Cliente();
        
        try {
            user.setEmail(emailCampoLogin.getText());
            user.setSenha(Integer.parseInt(String.valueOf(passwordCampoLogin.getPassword())));

        
            Connection con = null;        
            con = ConectarBD.abrirConexao();        
            ConsultaBD verificaUsuario = new ConsultaBD(con);

            if(verificaUsuario.verificaUsuarioSenha(user)){
                try {
                    user.setNome(verificaUsuario.retornaNomeUsuario(user));                    
                    MenuPrincipal main = new MenuPrincipal();
                    main.setVisible(true);
                    main.recuperaUsuario(user);
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();

            }else{
                JOptionPane.showMessageDialog(null, "Login inválido!", "Erro", 
                                                                     ERROR_MESSAGE);

                if(JOptionPane.showConfirmDialog(null, 
                                          "Deseja se cadastar?", "Primeiro acesso?", 
                                             YES_NO_OPTION, QUESTION_MESSAGE) == 0){

                    criaEmailCampoLogin.setText(emailCampoLogin.getText());
                    emailCampoLogin.setText(null);
                    passwordCampoLogin.setText(null);
                    criaNomeCampoLogin.setText(null);
                    criaNomeCampoLogin.grabFocus();
                    criaSenhaCampoLogin.setText(null);
                    confirmaSenhaCampoLogin.setText(null);



                }else{
                    emailCampoLogin.setText(null);
                    emailCampoLogin.grabFocus();
                    passwordCampoLogin.setText(null);
                }
            }
            user = null;
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_entrarBotaoActionPerformed

    private void criarContaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarContaBotaoActionPerformed
        try {
            // TODO add your handling code here:
            Cliente user = new Cliente(criaNomeCampoLogin.getText(), 
                            criaEmailCampoLogin.getText(), 
                            Integer.parseInt(String.valueOf(criaSenhaCampoLogin.getPassword())));
            
            Connection con = null;        
            con = ConectarBD.abrirConexao();        
            ConsultaBD verificaUsuario = new ConsultaBD(con);
            InsereBD insereUsuario = new InsereBD(con);

            if(!criaNomeCampoLogin.getText().isEmpty() 
                    && !criaEmailCampoLogin.getText().isEmpty()
                    && criaSenhaCampoLogin.getPassword().length > 0 
                    && confirmaSenhaCampoLogin.getPassword().length > 0){

                if(Arrays.equals(criaSenhaCampoLogin.getPassword(), confirmaSenhaCampoLogin.getPassword())){
                    if(verificaUsuario.verificaUsuario(user)){
                        JOptionPane.showMessageDialog(null, 
                          "Usuario já existe! Faça o login.", "Erro",ERROR_MESSAGE);

                        emailCampoLogin.setText(criaEmailCampoLogin.getText());
                        criaNomeCampoLogin.setText(null);
                        criaEmailCampoLogin.setText(null);
                        criaSenhaCampoLogin.setText(null);
                        confirmaSenhaCampoLogin.setText(null);
                        passwordCampoLogin.grabFocus();

                    }else{
                        
                        if(insereUsuario.inserirUsuario(user)){
                            JOptionPane.showMessageDialog(null, 
                                    "Usuário registrado com sucesso! ", "Sucesso", PLAIN_MESSAGE);

                            JOptionPane.showMessageDialog(null,
                                            user.getNome()
                                                            +", faça seu login!", 
                                                              "Sucesso", 
                                                              PLAIN_MESSAGE);
                            emailCampoLogin.setText(criaEmailCampoLogin.getText());
                            emailCampoLogin.grabFocus();
                            criaNomeCampoLogin.setText(null);
                            criaEmailCampoLogin.setText(null);
                            criaSenhaCampoLogin.setText(null);
                            confirmaSenhaCampoLogin.setText(null);
   
                        }else{
                            JOptionPane.showMessageDialog(null,
                                            "Erro ao gravar os dados!"
                                            + "Tente novamente!", 
                                            "Erro",ERROR_MESSAGE);
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, 
                           "Senha não confere! Tente novamente.", 
                           "Erro",ERROR_MESSAGE);

                    criaSenhaCampoLogin.setText(null);
                    confirmaSenhaCampoLogin.setText(null);
                    criaSenhaCampoLogin.grabFocus();
                }

            }else{
                JOptionPane.showMessageDialog(null, 
                           "Necessário peencher os campos de cadastro!", 
                           "Erro",ERROR_MESSAGE);
                criaNomeCampoLogin.grabFocus();
            }
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_criarContaBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmaSenhaCampoLogin;
    private javax.swing.JTextField criaEmailCampoLogin;
    private javax.swing.JTextField criaNomeCampoLogin;
    private javax.swing.JPasswordField criaSenhaCampoLogin;
    private javax.swing.JButton criarContaBotao;
    private javax.swing.JTextField emailCampoLogin;
    private javax.swing.JButton entrarBotao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordCampoLogin;
    // End of variables declaration//GEN-END:variables
}
